displayName=Port Roberts Thieving Helper
author=mkwozniak
description=A helper plugin for thieving stalls at Port Roberts.
tags=thieving, helper
plugins=com.prthievinghelper.PRThievingHelperPlugin
build=standard